ALTER TABLE receive_lots
    DROP COLUMN IF EXISTS packSize;
ALTER TABLE receive_lots
    ADD COLUMN packSize CHARACTER VARYING(200) DEFAULT NULL;


    ALTER TABLE asn_lots
    DROP COLUMN IF EXISTS packSize;
ALTER TABLE asn_lots
    ADD COLUMN packSize CHARACTER VARYING(200) DEFAULT NULL;