package org.openlmis.core.audit;

public enum AuditAction {
    CREATE,
    DISABLE,
    ENABLE,
    CHANGE_CODE,
    CHANGE_NAME,
    CHANGE_LEVEL,
    CHANGE_UNIT,
    CHANGE_DOSESPERDISPENSINGUNIT,
    CHANGE_PACKSIZE,
    CHANGE_MSLPACKSIZE,
    CHANGE_PACKROUNDINGTHRESHOLD,
    CHANGE_DISPENSINGUNIT,
    CHANGE_FACILITYTYPE_NAME
}